frameColor: "#6f42f5" # table frame color (HEX)
pointsColor: ""        # points color in the table (HEX)
logColor: "#404040"    # informational messages color (HEX)
warnColor: "#b84c44"   # warnings and errors color (HEX)

threadCount: 3          # number of parallel profiles
startDelay:             # random delay range before starting the next profile (hh:mm:ss)
  - "00:00:01"
  - "00:00:05"

retries: 5             # number of retry attempts on page load failure or other errors
messageDelay:          # delay range between messages (hh:mm:ss)
  - "00:00:00"
  - "00:00:02"
